Fixed exception when the destination path does not exist in the "upload" function.
Villain > upload /tmp/test.txt
Traceback (most recent call last):
  File "/usr/share/villain/Villain.py", line 1534, in <module>
    main()
  File "/usr/share/villain/Villain.py", line 1162, in main
    Hoaxshell.activate_pseudo_shell_session(session_id, os_type)
  File "/usr/share/villain/Core/villain_core.py", line 934, in activate_pseudo_shell_session
    File_Smuggler.upload_file(file_contents, cmd_list[2], session_id)
                                             ~~~~~~~~^^^
IndexError: list index out of range